# Generated by Django 2.2.5 on 2019-10-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_access_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Organisation', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
